# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 630168034893.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-web-app .
      - docker tag my-web-app:latest 630168034893.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 630168034893.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest
      - echo Build completed on `date`

artifacts:
  files: '**/*'
