version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running lint...
      - npm run lint
      - echo Building the application...
      - npm run build
      - echo Running tests...
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
